import {FicheModel} from './fiche.model';

export const MOCK_FICHES: FicheModel[] = [
    {
        id: 12,
        nom: 'Sylvestre',
        prenom: 'David',
        arrive: '000',
        depart: '001',
        temps: '1',
        positionRoue: 'gauche',
        nomClient: 'blah',
        nomAdresse: 'blah',
        dimension: 'blah',
        dimensionLibre: 'blah',
        nvh: 'blah',
        kmCompteur: 'blah',
        demontage: 'blah',
        depose: 'blah',
        reparation: 'blah',
        chaair: 'blah',
        retaillage: 'blah',
        emplatre: 'blah',
        forfait: 'blah',
        observation: 'blah',
        numeroPneu: 'blah',
        pression: 'blah',
        serrage: 'blah',
        fournitures: [],
        signatureClient: 'blah',
        signatureResponsable: 'blah',
        aEnvoyer: false,
        envoye: true,
},
    {
        id: 13,
        nom: 'Sylvestre',
        prenom: 'David',
        arrive: '000',
        depart: '001',
        temps: '1',
        positionRoue: 'gauche',
        nomClient: 'bleh',
        nomAdresse: 'blah',
        dimension: 'blah',
        dimensionLibre: 'blah',
        nvh: 'blah',
        kmCompteur: 'blah',
        demontage: 'blah',
        depose: 'blah',
        reparation: 'blah',
        chaair: 'blah',
        retaillage: 'blah',
        emplatre: 'blah',
        forfait: 'blah',
        observation: 'blah',
        numeroPneu: 'blah',
        pression: 'blah',
        serrage: 'blah',
        fournitures: [],
        signatureClient: 'blah',
        signatureResponsable: 'blah',
        aEnvoyer: true,
        envoye: false,
}
]
